Module3 task1
htmlacademy-adaptive/1838119-cat-energy-24 pull request #5
Opened 2021-12-04 03:09 UTC by Littlberdova

2021-12-06 09:24 UTC, craz3r requested changes

2021-12-06 09:24 UTC, craz3r commented on source/less/components/additional-catalog.less
> +.additional-catalog__item__header {
Невалидный БЭМ класс, нельзя использовать 2 бэм элемента в одном классе

2021-12-06 09:24 UTC, craz3r commented on source/less/components/additional-catalog.less
> +.additional-catalog__item__ammount,
то же самое, см комментарий выше

2021-12-06 09:24 UTC, craz3r commented on source/less/components/additional-catalog.less
> +.present {
Стили для бэм блока present нужно вынести в отдельный файл

2021-12-06 09:24 UTC, craz3r commented on source/less/components/address.less
> +.map-wrapper {
стили для блока map-wrapper нужно вынести в отдельный файл

2021-12-06 09:24 UTC, craz3r commented on source/less/components/catalog-header.less
> +.catalog__header__title {
Невалидный бэм класс

2021-12-06 09:24 UTC, craz3r commented on source/less/components/catalog.less
> +.catalog__item__header {
Невалидный бэм класс

2021-12-06 09:24 UTC, craz3r commented on source/less/components/catalog.less
> +.catalog__item__numbers {
то же самое

2021-12-06 09:24 UTC, craz3r commented on source/less/components/catalog.less
> +.catalog__item__note {
и тут

2021-12-06 09:24 UTC, craz3r commented on source/less/components/catalog.less
> +.catalog__item__comment {
и тут

2021-12-06 09:24 UTC, craz3r commented on source/less/components/catalog.less
> +.catalog__item__button {
и тут

2021-12-06 09:24 UTC, craz3r commented on source/less/components/catalog.less
> +.button-show-all {
для этого бэм блока нужен отдельный файл

2021-12-06 09:24 UTC, craz3r commented on source/less/components/client-example.less
> +@client-example-bg-color: #EAEAEA;
Вынесите эту переменную в файл со всеми переменными

2021-12-06 09:24 UTC, craz3r commented on source/less/components/client-example.less
> +.client-example__numbers__summary {
Невалидный бэм класс

2021-12-06 09:24 UTC, craz3r commented on source/less/components/client-example.less
> +.client-example__numbers__data {
невалидный бэм класс

2021-12-06 09:24 UTC, craz3r commented on source/less/components/client-example.less
> +.client-example__numbers__name {
невалидный бэм класс

2021-12-06 09:24 UTC, craz3r commented on source/less/components/form-header.less
> +.form__header {
Стили для бэм блока form должны лежать в файле form. Этот файл называется form-header - соотвественно здесь должны находиться стили для бэм блока form-header

2021-12-06 09:24 UTC, craz3r commented on source/less/components/form.less
> +.form__fill__group__list {
Невалидный бэм класс

2021-12-06 09:24 UTC, craz3r commented on source/less/components/form.less
> +.form__fill__group {
Невалидный бэм класс

2021-12-06 09:24 UTC, craz3r commented on source/less/components/form.less
> +.form__fill__group__name {
и тут

2021-12-06 09:24 UTC, craz3r commented on source/less/components/form.less
> +.form__fill__label {
и тут

2021-12-06 09:24 UTC, craz3r commented on source/less/components/form.less
> +input::placeholder,
Не используйте глобальные стили тегов

2021-12-06 09:24 UTC, craz3r commented on source/less/components/form.less
> +.form__fill__note {
Невалидный бэм класс

2021-12-06 09:24 UTC, craz3r commented on source/less/components/go-to-form-section.less
> +@go-to-form-text-color: #ffffff;
Перенести в файл с константами

2021-12-06 09:24 UTC, craz3r commented on source/less/components/page-footer.less
> +@footer-bg-color: #F2F2F2;
Перенести в файл с константами

2021-12-06 09:24 UTC, craz3r commented on source/less/components/page-header.less
> +@header-navigation-link-color: #000000;
Перенести в файл с константами

2021-12-06 09:24 UTC, craz3r commented on source/less/components/page-header.less
> +.site-list {
Стили для блока site-list перенести в соответствующий файл

2021-12-06 09:24 UTC, craz3r commented on source/less/components/program-type-section.less
> +@program-type-bg-color: #F2F2F2;
Перенести в константы

2021-12-06 09:24 UTC, craz3r commented on source/less/components/program-type-section.less
> +  font-family: "Oswald", sans-serif;
Задайте один раз шрифт для body и не придется его определять в каждом классе

2021-12-07 07:27 UTC, Littlberdova commented on source/less/components/additional-catalog.less
> +.additional-catalog__item__header {
+

2021-12-07 07:28 UTC, Littlberdova commented on source/less/components/additional-catalog.less
> +.additional-catalog__item__ammount,
+

2021-12-07 08:04 UTC, Littlberdova commented on source/less/components/program-type-section.less
> +  font-family: "Oswald", sans-serif;
я задавала на body шрифт Arial

2021-12-07 15:10 UTC, merged